### ISSUE TITLE
MostRecentlyUsedCache

### ISSUE THREAD

**Issue by MarkusTischendorf** [mattwar/iqtoolkit#10]
Hi Matt,

i think there is an issue in the **MastRecentlyUsedCache** class in method **Lookup**.

The method is always returing the last query not the one it found:

 ```csharp
for (int i = 0, n = this.list.Count; i < n; i++)
{
    cached = this.list[i];

    if (fnEquals(cached, item))
    {
         cacheIndex = 0;
    }
}
```

I think this should be correct:

 ```csharp
for (int i = 0, n = list.Count; i < n && cacheIndex < 0; i++)
{
    cached = this.list[i];

    if (_fnEquals(cached, item))
    {
        cacheIndex = i;
    }
}
```

The for-loop is two times in that method.

Thanks and best regards,

Markus

**Comment by mattwar** [comment]
Yes, that code was wrong.  bad code!

As far as I can tell, it was returning the found item, it was just never updating the MRU list.

I really need some unit tests for these common classes. 😞 

I've fixed it with this change:  https://github.com/mattwar/iqtoolkit/pull/11/commits/a708c62d6646f5156de5970a18626c4cec2fe096
