### ISSUE TITLE
Add Links to the "Building a LINQ IQueryable Provider" series of posts

### ISSUE THREAD

**Issue by MattMinke** [mattwar/iqtoolkit#18]
I remember reading these post a long time ago and I found them to be beneficial for understanding the inner workings of this project. I think it would be nice to have this content either copied to GitHub, or linked to from this repository. I would lean toward centralizing the content on GitHub but that's just my preference. 

https://blogs.msdn.microsoft.com/mattwar/2008/11/18/linq-building-an-iqueryable-provider-series/
Part I - [Reusable IQueryable base classes](https://blogs.msdn.microsoft.com/mattwar/2007/07/30/linq-building-an-iqueryable-provider-part-i/)
Part II - [Where and reusable Expression tree visitor](https://blogs.msdn.microsoft.com/mattwar/2007/07/31/linq-building-an-iqueryable-provider-part-ii/)
Part III - [Local variable references](https://blogs.msdn.microsoft.com/mattwar/2007/08/01/linq-building-an-iqueryable-provider-part-iii/)
Part IV - [Select](https://blogs.msdn.microsoft.com/mattwar/2007/08/02/linq-building-an-iqueryable-provider-part-iv/)
Part V - [Improved Column binding](https://blogs.msdn.microsoft.com/mattwar/2007/08/03/linq-building-an-iqueryable-provider-part-v/)
Part VI - [Nested queries](https://blogs.msdn.microsoft.com/mattwar/2007/08/09/linq-building-an-iqueryable-provider-part-vi/)
Part VII - [Join and SelectMany](https://blogs.msdn.microsoft.com/mattwar/2007/09/04/linq-building-an-iqueryable-provider-part-vii/)
Part VIII - [OrderBy](https://blogs.msdn.microsoft.com/mattwar/2007/10/09/linq-building-an-iqueryable-provider-part-viii/)
Part IX - [Removing redundant subqueries](https://blogs.msdn.microsoft.com/mattwar/2008/01/16/linq-building-an-iqueryable-provider-part-ix/)
Part X – [GroupBy and Aggregates](https://blogs.msdn.microsoft.com/mattwar/2008/07/08/linq-building-an-iqueryable-provider-part-x/)
Part XI - [More of everything](https://blogs.msdn.microsoft.com/mattwar/2008/07/14/linq-building-an-iqueryable-provider-part-xi/)
Part XII - [Relationships and the IQ Toolkit](https://blogs.msdn.microsoft.com/mattwar/2008/11/17/building-a-linq-iqueryable-provider-part-xii/)
Part XIII - [Updates and Batch Processing](https://blogs.msdn.microsoft.com/mattwar/2009/01/22/building-a-linq-iqueryable-provider-part-xiii/)
Part XIV - [Mapping and Providers](https://blogs.msdn.microsoft.com/mattwar/2009/04/08/building-a-linq-iqueryable-provider-part-xiv/)
Part XV - [Transactions, Sessions and Factories](https://blogs.msdn.microsoft.com/mattwar/2009/06/16/building-a-linq-iqueryable-provider-part-xv-iqtoolkit-v0-15/)
Part XVI - [Performance and Caching](https://blogs.msdn.microsoft.com/mattwar/2009/09/15/building-a-linq-iqueryable-provider-part-xvi-iqtoolkit-0-16/)
Part XVII - [Automatic Caching and Loading Policies](https://blogs.msdn.microsoft.com/mattwar/2010/02/09/building-a-linq-iqueryable-provider-part-xvii-iqtoolkit-0-17/)

**Comment by CrossBound** [comment]
Agreed... Looks like in the first post there is a link that is supposed to go to the list of posts, but the link is broken. Also it appears that https://docs.microsoft.com/en-us/dotnet/api/system.linq.iqueryable-1?view=netframework-4.8 sends you to the first post.... wonder if somewhere we could get a final list of posts and then have the docs.microsoft.com article point to the new location.

The difinitive list as far as I know is here: https://blogs.msdn.microsoft.com/mattwar/2008/11/18/linq-building-an-iqueryable-provider-series/

Not sure if there are any updates since then.

**Comment by mattwar** [comment]
Added posts to docs/blog directory.  Slowly in process of converting them to better markdown.

**Comment by moh-hassan** [comment]
All series blogs of @mattwar  as markdown files are available [here](https://github.com/mattwar/iqtoolkit/tree/master/docs/blog)
