### ISSUE TITLE
Distinct/Case combination

### ISSUE THREAD

**Issue by MarkusTischendorf** [mattwar/iqtoolkit#8]
Hi,

i think a combination of Distinct and a case expression is not working like expected.

Example:
 ```
var query = db.Customers.Select(r => r.CustomerID == "ALFKI" ? 1 : 0).Distinct();

var test = query.ToList();
Assert.Equal(2, test.Count());
```
The sql query includes the column CustomerID and the case is evaluated locally. 
This results in more than 2 rows.

Thanks...
Markus

**Comment by mattwar** [comment]
Thanks for the report.  I've fixed this in the current source.
